# Generated by Django 4.2.6 on 2023-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceAndPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=100, verbose_name="название сервиса"),
                ),
                (
                    "hashed_password",
                    models.CharField(
                        max_length=300, verbose_name="Зашифрованный пароль"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "сервис и пароль",
                "verbose_name_plural": "сервисы и пароли",
            },
        ),
    ]
