# Generated by Django 4.2.6 on 2023-10-28 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passwords", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceAndPassword",
            new_name="Service",
        ),
    ]
