# Generated by Django 4.2.6 on 2023-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_rename_serviceandpassword_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Зашифрованный пароль'),
        ),
    ]
